apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestfarma-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gestfarma-backend
  template:
    metadata:
      labels:
        app: gestfarma-backend
    spec:
      containers:
        - name: backend
          image: gestfarma-backend:latest
          imagePullPolicy: Never # Usa a imagem compilada localmente no minikube
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: gestfarma-config
            - secretRef:
                name: gestfarma-secret
