apiVersion: v1
kind: Secret
metadata:
  name: gestfarma-secret
type: Opaque
stringData:
  DB_USER: <SEU_DB_USER_AQUI>
  DB_PASSWORD: <SUA_DB_PASSWORD_AQUI>
  POSTGRES_USER: <SEU_DB_USER_AQUI>
  POSTGRES_PASSWORD: <SUA_DB_PASSWORD_AQUI>
  POSTGRES_DB: <SEU_DB_NAME_AQUI>
  JWT_SECRET: <SUA_CHAVE_SECRETA_JWT_BASE64_AQUI>
