spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:farmacia}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.fail-on-missing-locations=true
spring.jpa.hibernate.ddl-auto=none
spring.flyway.validate-on-migrate=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha

jwt.secret=${JWT_SECRET:2rzuSery6O9JucO5VvseVp8LwxmdghCb0EmUYylD9Fe3Mkf3V/M2Uqy4dqXkUSz4ZIxGaZZRF+h/Hww+umbH2Q==}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}